### ISSUE TITLE
Accepting TOS automatically

### ISSUE THREAD

**Issue by AbelIngrand** [FrostTheFox/ptc-acc-gen#1]
Hi

I'm not a Node JS developer so I'm not sure how to implement this but in case you didn't know, there's a script to automaticly accept the TOS using the POGOAPI written in Python here https://github.com/scottstamp/pgoapi/blob/master/scripts/accept-tos.py

I guess it shouldn't be too hard to implement a batch script when the Node JS  API will be updated..

**Comment by FrostTheFox** [comment]
Looking into this.

**Comment by FrostTheFox** [comment]
Going to be included very shortly.
