### ISSUE TITLE
Problem when Signup page is in Maintenance mode...

### ISSUE THREAD

**Issue by jayGathoni** [FrostTheFox/ptc-acc-gen#11]
Script ends up with:

creating account 0 of 200
[DEBUG] Handle first page #0
Find the generated accounts in PogoPlayer/accounts.csv

Took me some minutes to figure out Signup page was down.
Maybe catch that error in your script.

Regards, Jay.

**Comment by LegITdevel** [comment]
Same error here without the sign-up page to be down...

**Comment by pyr0ball** [comment]
@LegITdevel are you running from SSH or a teminal within a GUI? the node.js script for ptc-gen requires a GUI interface to work correctly

**Comment by LegITdevel** [comment]
SSH via Putty :P ok, closed

**Comment by pyr0ball** [comment]
@LegITdevel @jayGathoni new commit that accounts for headless linux installs. Give it another try now

**Comment by pyr0ball** [comment]
@LegITdevel @jayGathoni is this resolved for you guys?

**Comment by FrostTheFox** [comment]
Closing, seemed like a headless problem rather than a response problem. Open new issue if persists.

**Comment by jayGathoni** [comment]
Excellent work bro!!
