### ISSUE TITLE
Account name too long + other stuff

### ISSUE THREAD

**Issue by razorasadsid** [FrostTheFox/ptc-acc-gen#12]
Gonna see what happens if I flip and switch stuff around. Maybe I do just need a shorter name =/
http://image.prntscr.com/image/07259fffd20b4dadb721f9356f77a96b.png
http://image.prntscr.com/image/1fc5e172bd254f978e07de3e70f4aab7.png

**Comment by FrostTheFox** [comment]
Are you just getting this from the ToS accepter? Or the account script itself?

**Comment by kinderoth** [comment]
I'm getting the Stoperror: status code 3 recieved from RPC. this is from the Tos Acceptor I imagine? It makes the accounts but i get this after the next step.

**Comment by razorasadsid** [comment]
Account script itself.

**Comment by razorasadsid** [comment]
http://image.prntscr.com/image/22797a768fa14d3c9b5b7a31fa146bcd.png

**Comment by FrostTheFox** [comment]
All these screenshots you're showing me are coming from the ToS accepter, which we're using MRokas's PogoPlayer for. This would be better suited on his github https://github.com/MRokas/PogoPlayer. Code 3 from RPC means that the account returned verified when it attempted to verify it. 

The 12 characters is it trying to set the trainer name.
