### ISSUE TITLE
Steps to run incomplete?

### ISSUE THREAD

**Issue by Tuumi** [FrostTheFox/ptc-acc-gen#13]
git clone https://github.com/FrostTheFox/ptc-acc-gen
cd ptc...
npm install

(no errors, mainly few warns about nintendo-ptc-account-generator@1.3.0 No repository field.  and No license field.)

Little fiddling with index.js var's (like setting nicknames.json true etc)

node index.js -> 

x@ubuntu:~/ptc-acc-gen$ node index.js
Creating account 0 of 10
[DEBUG] Handle first page #0
x@ubuntu:~/ptc-acc-gen$

if I run makeaccounts.sh it just makes the same and then tells me that generated accounts can be viewed from the PogoPlayer/accounts.csv file (which is there - but it's empty)

So, what am I missing (running under 16.04 LTS ubuntu with 6.x nodejs)

**Comment by Tuumi** [comment]
(Arh. Nevermind. Noticed another open issue and statement that this thing doesnt work in cli.. Shame..)

**Comment by FrostTheFox** [comment]
Yep, unfortunately does not work in cli.
