### ISSUE TITLE
Can't Create Accounts

### ISSUE THREAD

**Issue by jsl303** [FrostTheFox/ptc-acc-gen#14]
When I run the script, I get this.
Creating account 0 of 10                                                        
[DEBUG] Handle first page #0                                                    
Find the generated accounts in PogoPlayer/accounts.csv                           
The csv is empty.
Here are the settings I changed from the default.
var useRandomPassword = false;
var username = "username";
var password = "password";
var email_user = "email(without @gmail.com)";
var email_domain = "gmail.com";
var lat = "##.######";
var lon = "-##.######";
I checked the ptc sign up page, and it seems to work.
Any suggestion?`

**Comment by FrostTheFox** [comment]
What're you running on?

**Comment by jsl303** [comment]
Ubuntu 16.04.

**Comment by FrostTheFox** [comment]
Are you running on cli? You need to run this from a gui.

**Comment by jsl303** [comment]
Ah, that explains.

I just ran on Windows, and it seemed to work.

Thanks!

**Comment by FrostTheFox** [comment]
No problem.
