### ISSUE TITLE
[Request] Remove GUI Requirement

### ISSUE THREAD

**Issue by johnkernke** [FrostTheFox/ptc-acc-gen#15]
Please give an option to run this without a GUI installed. My server doesn't (and can't) have a GUI installed on it, and I don't want to setup everything on my local machine just for creating accounts. I don't see any reason for requiring this other than taking screenshots of pages which I don't want anyway.

**Comment by FrostTheFox** [comment]
Please try using `sudo apt-get install xvfb`, (or your distro's equivalent) and running `DEBUG=nightmare xvfb-run --server-args="-screen 0 1024x768x24" ./makeaccounts.sh`.

**Comment by tlundse** [comment]
I ran this under xvfb-run and it worked for me.

**Comment by pyr0ball** [comment]
#17 #18 added functions to allow for headless server runs

**Comment by FrostTheFox** [comment]
Merging #17 and #18. Issue no longer relevant.
