### ISSUE TITLE
accounts not showing

### ISSUE THREAD

**Issue by DionVermeulen** [FrostTheFox/ptc-acc-gen#16]
the gen is working and also screenshots, but there are no accounts in accounts.csv.
the gen won't output it to the file.
please help me :)

**Comment by tratata42** [comment]
Had similar problem (Windows 10 bat). I think it happens for accounts that failed TOS acceptance. Only 7 out of 11 went into pogoplayer/accounts.csv and the rest did not. Screenshots were present for 11 and I was able to accept TOS on the 4 remaining later. Still they should be in csv (maybe another one) to be able to get their passwords if randomly generated.

**Comment by MRokas** [comment]
ToS accept script does not generate .csv, it's generated by account creator.

**Comment by tratata42** [comment]
sorry my bad, I do see in screenshots that 0-3 worked, 4-7 said "this email address is already associated with an account" and 8-10 worked. Strangely, I got verification emails for all 11. But in the end 4-7 didnt make it to csv and subsequently to the tos verifier, maybe it's the same problem for DionVermeulen, what the screens say?

**Comment by DionVermeulen** [comment]
http://imgur.com/a/4LYOE
all of the screenshots are that one above but with other names
does the red line mean its already used?

**Comment by MRokas** [comment]
Yes, red outline suggests username is already taken.

**Comment by DionVermeulen** [comment]
okay im gonna look if i put another username in it

**Comment by DionVermeulen** [comment]
thanks now it's working!! :+1:

**Comment by DionVermeulen** [comment]
but very slow.
is there a way to make it faster?

**Comment by DionVermeulen** [comment]
and can i use this in the command line on ubuntu server?

**Comment by MRokas** [comment]
At the moment usage in CLI servers(not sure on their actual name..) isn't supported.

**Comment by FrostTheFox** [comment]
The GUI requirement is not something we're going to change, but we might include a workaround for headless servers.

**Comment by pyr0ball** [comment]
headless linux server workaround added in #17 #18

**Comment by FrostTheFox** [comment]
Is this issue fixed? @DionVermeulen

**Comment by driannaude** [comment]
Just like to throw in another question for @DionVermeulen here, because it seems an easy thing to miss, but did you check the CSV in `PogoPlayer/accounts.csv` or just the one in `/output` ??
@FrostTheFox and @pyr0ball, I think the `accounts.csv` in the output is a little confusing. It's actually the first place I looked as well, and then I remembered the PogoPlayer dir from the documentation. P.S. Great tool!

**Comment by DionVermeulen** [comment]
@FrostTheFox  yeah it's fixed

**Comment by pyr0ball** [comment]
@driannaude good point, I'll update the echo behavior to reflect that

**Comment by pyr0ball** [comment]
Issue resolved
