### ISSUE TITLE
Error message to run tutorials

### ISSUE THREAD

**Issue by xioxxio** [FrostTheFox/ptc-acc-gen#20]
The accounts are being generated in the accounts.csv

When the script runs, there is an error message the tutorial failed to run?

**Comment by pyr0ball** [comment]
the ToS portion of the script may have been running into issues due to server lag or there may be a problem with the username being too long

**Comment by FrostTheFox** [comment]
Support's been dropped for this tool. Please use https://github.com/skvvv/pikapy.
