### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by NGPriest** [FrostTheFox/ptc-acc-gen#21]
Using SSH over Putty.

~/ptc-acc-gen$ node index.js
Creating account 0 of 100
[DEBUG] Handle first page #0
~/ptc-acc-gen$

**Comment by CtrlAltDefeat94** [comment]
Ran it overnight on Windows 10 and this is all the output I got;
`makeaccounts.bat
Creating account 0 of 50
`

**Comment by plgonzalezrx8** [comment]
Mine got stuck at creating account 8 out of 10 and thats it, and I cannot find the password for the 8 created accounts because it never wrote the file

**Comment by Vardex** [comment]
Worked yesterday now, it's creating account but never write it in the file or take screenshot and most of the time it crash around 8 created account

**Comment by pyr0ball** [comment]
@NGPriest thats what it looks like when you're running this on ssh without a gui, and before we implemented the workaround in #17 & #18 

We're still working on fixing the hanging issue

**Comment by FrostTheFox** [comment]
Closing this issue because the OP is not using the new .sh, which prevents this issue.

**Comment by NGPriest** [comment]
I was in a chat and they told me to apt-get a new package...

Still gets stuck on the 8th...
