### ISSUE TITLE
xvfb-run command not found error on OSX

### ISSUE THREAD

**Issue by c133** [FrostTheFox/ptc-acc-gen#23]
Hello, first of all thank you for this wonderful script. I have been using it the past few days. After pulling recent commits, I am not able to run the script. I did

./install.sh
npm install xvfb

but aftewards the xvfb-run command cannot be found. From google it looks like X11 on osx does not have xvfb (I guess older versions like X10 did) so basically, is there a way to get xvfb-run working on osx? Right now I am just running using

node index.js

without the headless xvfb.

**Comment by pyr0ball** [comment]
xvfb is a linux only package afaik. It's designed to be used only on headless systems. If you're on OSX and are using a full desktop, you can simply omit that part of the script.

Apologies as I don't have an OSX system to test this on

**Comment by FrostTheFox** [comment]
Pyr0 is correct. Simply omit the xvfb portion.
