### ISSUE TITLE
electron child process

### ISSUE THREAD

**Issue by Heavywavez** [FrostTheFox/ptc-acc-gen#24]
Hello i'm having this issue:

` nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly +22ms
  nightmare electron child process not started yet, skipping kill. +0ms`

I'm Already run  `npm install -g electron` wich i had no 0 error's after install. 

But still showing same error code, any ideas? i'm running on Ubuntu Server. 

Thanks.

**Comment by pyr0ball** [comment]
try running as sudo on requirements.txt?

`sudo npm install`

**Comment by Heavywavez** [comment]
@pyr0ball  i did again and still same problem..

` nightmare queuing process start +0ms
  nightmare queueing action "useragent" +4ms
Creating account 0 of 10
  nightmare queueing action "goto" for https://club.pokemon.com/us/pokemon-trainer-club/sign-up/ +6ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +1ms
  nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly +21ms
  nightmare electron child process not started yet, skipping kill. +1ms
Find the generated accounts in PogoPlayer/accounts.csv`

**Comment by tristaoeast** [comment]
exactly same problem here

**Comment by lindi200000** [comment]
Hi, i have the same problem too.
Any Ideas?
OS: Ubuntu 16.04 LTS

**Comment by Ogeru** [comment]
worked for me after :
apt-get install -y libgtk2.0-0 libgconf-2-4 libasound2 libxtst6 libxss1 libnss3 xvfb

See: https://github.com/segmentio/nightmare/issues/224

**Comment by tristaoeast** [comment]
@Ogeru you running it in what OS? Is it headless? Because the conclusion I reached from reading that reference is that this problem seems to be related to headless linux distros. I was having this problem when running it from a VPS with Ubuntu Server, when I ran it in Ubuntu Desktop it ran just fine.

**Comment by tristaoeast** [comment]
Installing the packages that Ogeru referenced and changing the script like @johnkernke described in #22  seems to have made it work with headless Ubuntu Server running in a VPS

**Comment by remcotroost** [comment]
Had the same issue as @Heavywavez and solved it by using the advice of @tristaoeast

**Comment by Heavywavez** [comment]
solver by doing what @Ogeru  say, just need add --force-yes

Thanks.

**Comment by FrostTheFox** [comment]
Support's been dropped for this tool. Please use https://github.com/skvvv/pikapy.
