### ISSUE TITLE
code 127 : command not found

### ISSUE THREAD

**Issue by ChrisbeChicken** [FrostTheFox/ptc-acc-gen#25]
hello i got this error while running makeaccount.sh

  nightmare queuing process start +0ms
  nightmare queueing action "useragent" +4ms
Creating account 0 of 10
  nightmare queueing action "goto" for https://club.pokemon.com/us/pokemon-trainer-club/sign-up/ +5ms
  nightmare queueing action "evaluate" +1ms
  nightmare running +0ms
  nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly +21ms
  nightmare electron child process not started yet, skipping kill. +1ms
Find the generated accounts in PogoPlayer/accounts.csv

the generated accounts.csv i still empty

**Comment by FrostTheFox** [comment]
Duplicate #24
