### ISSUE TITLE
Hang after creating ~6 accounts

### ISSUE THREAD

**Issue by c133** [FrostTheFox/ptc-acc-gen#28]
Hello all, I have experienced the script hanging on two separate instances. The other night after starting the script I noticed it pauses after creating ~6 accounts and does not continue. I tried again today and the same thing occured.

1. Has anyone else experienced this?
2. Is there any kind of verbose flag I can pass in to find out what's happening?

Thank you.

**Comment by yayes2** [comment]
Having the same. Turned on debug and got the following log
```
Creating account 14 of 100
[DEBUG] Handle first page #14
[DEBUG] Fill first page #14
[DEBUG] Handle second page #14
[DEBUG] Fill signup page #14
[DEBUG] Error:{}
[DEBUG] Handle second page #14
[14] Servers are acting up... Trying again.
[DEBUG] Handle first page #14
[DEBUG] Fill first page #14
[DEBUG] Handle second page #14
[DEBUG] Fill signup page #14
```

**Comment by c133** [comment]
Also gets stuck at "Fill signup page" for me

**Comment by FrostTheFox** [comment]
Support's been dropped for this tool. Please use https://github.com/skvvv/pikapy.
