### ISSUE TITLE
[OSX SUPPORT] Please add

### ISSUE THREAD

**Issue by DimaVIII** [FrostTheFox/ptc-acc-gen#29]
Hey Guys, I just added OSX support for the account gen. 

### Instruction
First install npm nodejs with brew, example:
```
sudo -H brew install npm
sudo -H brew install nodejs
```

1. Install https://www.xquartz.org/
2. `git clone --recursive -b master https://github.com/FrostTheFox/ptc-acc-gen.git`
3. `cd ptc-acc-gen`
4. `sudo -H npm install`
5. EDIT makeaccounts.sh to:
```
#!/bin/bash

DEBUG=nightmare Xvfb -screen 0 1024x768x8 & node index.js
cd PogoPlayer
DEBUG=nightmare Xvfb -screen 0 1024x768x8 & node pogo.js
echo "Find the generated accounts in PogoPlayer/accounts.csv"

```
### Run with
`sudo ./makeaccounts.sh`

**Comment by FrostTheFox** [comment]
Support's been dropped for this tool. Please use https://github.com/skvvv/pikapy.
