### ISSUE TITLE
I do not "UNDERSTAND" where the the code reading in the emails from because i am not getting any results.

### ISSUE THREAD

**Issue by Rikilsta** [FrostTheFox/ptc-acc-gen#36]
I follow the instructions but I have no understanding how the code works.
                    https://github.com/FrostTheFox/ptc-acc-gen/blob/master/gmailverify.js
Where is it reading in the emails from because when I run the code/script, it does not ask me to punch in the emails of the accounts I want to verify.

**Comment by FrostTheFox** [comment]
You uh, have to run it at script.google.com

Read the top of the code.

**Comment by Rikilsta** [comment]
I follow the instrutctions until # 5 thats when i was unsatisfied. 0 accounts verified.

**Comment by FrostTheFox** [comment]
And that specific google account is used in index.js?

**Comment by Rikilsta** [comment]
yes

**Comment by FrostTheFox** [comment]
And you can see the emails in gmail?

**Comment by Rikilsta** [comment]
No. I made a new email for the purpose of using google scripts.

**Comment by FrostTheFox** [comment]
You need to be signed into gmail using the account you defined in index.js, and use that same account in google scripts.

**Comment by Rikilsta** [comment]
thank you sir
