### ISSUE TITLE
created mailadress was: prefix + usernameofPTC + number @trash-mail.com

### ISSUE THREAD

**Issue by roflinger** [FrostTheFox/ptc-acc-gen#39]
> // Requires
var Nightmare = require('nightmare');
var nicknames = require('./nicknames.json');
var fs = require('fs');

// Settings
var debug = false;
var showWindow = true;

var start = 0; // Start from x (NAMEx, EMAIL+x@domain.com)
var end = 10;

var useNicknamesFile = false; // Use nicknames file, or just append numbers to username?
var useRandomPassword = false; // Generate a random password?
var screenshotResult = true; // Saves a screenshot per account creation if set to true
var screenshotOnFailure = true; // Saves a screenshot even if registration failed

var outputFile = "PogoPlayer/accounts.csv"; // File which will contain the generated "username password" combinations.
var outputFormat = "ptc,%NICK%,%PASS%,%LAT%,%LON%,%UN%\r\n"; // Format used to save the account data in outputFile. Supports %NICK%, %PASS%.
var screenshotFolder = "output/screenshots/";

var country = "US"; // Country code (e.g. BE, FR, US, CA)
var dob = "1990-01-01"; // Date of birth, yyyy-mm-dd
var username = "blubrerererer"; // User- & display name. Make sure any "(username + number)@domain.com" is 100% unique, and is 6 characters minimum, but under 14 characters after the numbers are applied.
var password = "xxxxx"; // Static password for all accounts. Ignored if useRandomPassword is true.
var email_user = "asdasdasdasa"; // If your email is email@domain.com, enter "email"
var email_domain = "trash-mail.com"; // Domain of e-mail host

what did i do wrong?

**Comment by roflinger** [comment]
thats what it looked like: asdasdasdasa+blubrerererer5@trash-mail.com

**Comment by FrostTheFox** [comment]
It's supposed to look like that.
