### ISSUE TITLE
Country always US

### ISSUE THREAD

**Issue by springjools** [FrostTheFox/ptc-acc-gen#40]
I tried editing the country code field in index.js and using the values "FI" and "SE" (for finland and sweden), I still always get registered using an US account

**Comment by FrostTheFox** [comment]
Interesting. Let me do some testing.

**Comment by springjools** [comment]
I guess the format of the country codes are the ISO Standard 3166: https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by FrostTheFox** [comment]
Yep, I can confirm that it doesn't seem to be properly setting the country. For now having them be US shouldn't change anything, but I'll look into it.

**Comment by FrostTheFox** [comment]
Been informed it IS actually changing, just doesn't show it visually.
