### ISSUE TITLE
PogoPlayer RPC Error 51

### ISSUE THREAD

**Issue by khag7** [FrostTheFox/ptc-acc-gen#41]
Anyone else getting an error when trying to run pogoplayer please see here:
https://github.com/MRokas/PogoPlayer/issues/6
https://github.com/cyraxx/pogobuf/issues/85

**Comment by pyr0ball** [comment]
could you paste the output?

**Comment by khag7** [comment]
when pogo.js runs to accept TOS, for each account I receive this message (formatting is my own, but the content of the message is the same:

```
Failed to initialize client...
ERROR: {
  [Error: operation timed out after 5061 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 51]
  failure: [Error: Fetching RPC endpoint failed, received status code 51],
  code: 'ETIMEDOUT'
}
```

![image](https://cloud.githubusercontent.com/assets/1531746/17828411/9ab3a884-665e-11e6-897a-68da13ec13f1.png)

`

**Comment by khag7** [comment]
PR for a fix is ready for review on the pogobuf repo, once that's merged and a release created I think you can just do `npm update` ... speaking of which, should the install.bat script include an npm update command to handle this situation (for those users who can't figure out how to do a simple command)
see:
https://github.com/cyraxx/pogobuf/pull/86

**Comment by FrostTheFox** [comment]
will be kept in mind on the install script, the windows one is still considered experimental.

**Comment by pyr0ball** [comment]
This is an issue with the submodule and dependancies. Once that gets fixed on the other repos, it'll automatically get fixed here since we're including them as a submodule and not just a copy. closing

**Comment by khag7** [comment]
I agree with the decision pyr0 EXCEPT that most people don't search the issues before submitting. I put it here as a FYI to preempt any other folks from submitting "OMG WTF Y U NO WORK"

**Comment by khag7** [comment]
pogobuf is updated.

`npm update`
