### ISSUE TITLE
Fetching RPC endpoint failed

### ISSUE THREAD

**Issue by xomikronx** [FrostTheFox/ptc-acc-gen#57]
Failed to initialize client... ERROR: { [Error: operation timed out after 4548 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 51]
  failure: [Error: Fetching RPC endpoint failed, received status code 51],
  code: 'ETIMEDOUT' }

this happens when `node pogo.js` is ran.

**Comment by xomikronx** [comment]
Seems like all accounts being created are automatically getting banned.

Anyone else?

**Comment by thisismohitgupta** [comment]
Just do it over a proxy and try , may be It will work somehow

**Comment by xomikronx** [comment]
You think it's associating it with a banned IP?

**Comment by FrostTheFox** [comment]
npm update

Not an issue with any of our tools, it's a pogobuf issue (one of pogoplayer's dependencies)

**Comment by FrostTheFox** [comment]
Please run `npm update`

Closing this issue for now, if it persists please use the discord link in the readme.
