### ISSUE TITLE
Kickback to console

### ISSUE THREAD

**Issue by coffman34** [FrostTheFox/ptc-acc-gen#6]
When running node index.js I get:

`Creating Account 0 of 10`

Then it kicks back to console.

Activating debug shows it stopping at Handle first page #0.

**Comment by FrostTheFox** [comment]
We're aware of this issue, still not quite sure of the cause. Looking into it.

**Comment by swablueme** [comment]
Same issue here.
Config: https://cdn.discordapp.com/attachments/204339169458126849/212035704576933889/unknown.png
node -v outputs v6.2.2
I have chowned the folder. I have NPM installed etc

**Comment by swablueme** [comment]
Using branch ToS test

**Comment by pyr0ball** [comment]
you MUST run on an x11 GUI terminal. required for the pages to load. ssh terminal will not work

**Comment by Phantisy** [comment]
Guess that is my problem. I have no GUI installed on my server.

**Comment by swablueme** [comment]
No GUI here either.

**Comment by pyr0ball** [comment]
I'd suggest installing xfce and running it from there with gnome-terminal

**Comment by Phantisy** [comment]
I will attempt to use a live cd on my system. I cannot install a GUI on my server. Thank you for the help!

**Comment by swablueme** [comment]
Fug I just found out the reason: 
<img src="http://i.imgur.com/csd611Z.png">
Error 500 upon trying to generate the accounts everyone

**Comment by swablueme** [comment]
Ok now it's acting up with the same error message even though reg should be working 
<img src="http://i.imgur.com/DwXLjdE.png">

**Comment by coffman34** [comment]
This problem was solved by using a Windows box to run the script. You can probably close this.
