### ISSUE TITLE
Parent Email is Required? Can't create an account

### ISSUE THREAD

**Issue by Niggster90** [FrostTheFox/ptc-acc-gen#65]
So just as the subject states, you need a parent email now?

**Comment by FrostTheFox** [comment]
Have you changed the DOB in index.js? What commit are you running off? OS?

**Comment by Niggster90** [comment]
Nevermind I'm not sure what happened but I tried it again and it worked.

**Comment by Niggster90** [comment]
It was on PC btw

**Comment by Niggster90** [comment]
Win 8.1

**Comment by FrostTheFox** [comment]
Sometimes random glitches like that happen, a lot of the times it's just something weird in the PTC response.
