### ISSUE TITLE
Feature Request - Script to test accounts from CSV for ban or bad credentials

### ISSUE THREAD

**Issue by ssteuteville** [FrostTheFox/ptc-acc-gen#66]
It would be awesome if there were a script available to test which accounts are still working and modify accounts.csv accordingly.

**Comment by FrostTheFox** [comment]
Once we generate the .csv, it's pretty much out of our control. There's https://github.com/a-moss/PoGoAccountCheck Maybe this would be more appropriate for the tools such as pokemongo-map that actually use the accounts.csv, and have them pull it out of rotation. It would in theory be possible to just modify the pogoaccountcheck, but i'd rather not have to bundle another thing along with it.

**Comment by ssteuteville** [comment]
Awesome. I wasn't aware of that utility. I might try to fork it and add the accounts.csv modification part myself.
