### ISSUE TITLE
Error creating accounts

### ISSUE THREAD

**Issue by MarksmanMoi** [FrostTheFox/ptc-acc-gen#67]
After I create the third accouts it trows me this error

" Servers are acting up... Trying again."

and the page don't reload or do anything

**Comment by FrostTheFox** [comment]
Try going View ---> Reload.

It's stuck at the 3rd page, yes?

**Comment by MarksmanMoi** [comment]
It is stuck in the "Create account" step didn't let me put the captcha, I try reload it a lot of times and didn't work

**Comment by MarksmanMoi** [comment]
Any update?

**Comment by FrostTheFox** [comment]
It's one of those things we really can't do anything about, it's just a thing that unfortunately happens. Try doing `npm uninstall nightmare` `npm uninstall pogobuf` and then delete the ptc-acc-gen folder and reclone. Hopefully a reinstall will help.

**Comment by MarksmanMoi** [comment]
Do you recommend me to install it as you write with the recursive? or download master and do all the other rules?

**Comment by FrostTheFox** [comment]
recursive

**Comment by MarksmanMoi** [comment]
It work :) Thanks a lot Frost :D

**Comment by MarksmanMoi** [comment]
It worked for 7 accounts now, not sure why that error is showing up :/

**Comment by FrostTheFox** [comment]
well, it's likely not something *really* fixable, but you can change the first number in `config.js` to be the number that it stopped before, and it'll continue from where you left off.

**Comment by MarksmanMoi** [comment]
Find my mistake, but need some help, in the config.js, what should I introduce in the username ? and password? just let them empty? or how can i configure all that file

**Comment by FrostTheFox** [comment]
if you want to start where you left off, you need to know the number it stopped at. So, if it made the 7th account but stopped, you'd change startNum:0, to startNum:8,

**Comment by FrostTheFox** [comment]
If you're still having issues, you can use the PokemonGo-Map discord for support. (link in the readme)
