### ISSUE TITLE
Inverted date

### ISSUE THREAD

**Issue by obsess** [FrostTheFox/ptc-acc-gen#68]
After about 7-10 accounts it will flip the date from 01-01-1990 to 1990-01-01 and cause a parent or guardian warning. The program will then keep pressing back and doing it over and over again until close.

**Comment by FrostTheFox** [comment]
Looking into it and trying to reproduce.

**Comment by obsess** [comment]
It has randomly happened 3 times. Tried to reproduce twice but couldn't get it to. If I can do anything to help debugging when it happens again let me know.

**Comment by FrostTheFox** [comment]
Windows or linux?

**Comment by obsess** [comment]
Windows 10 pro

**Comment by FrostTheFox** [comment]
run manually using `SET DEBUG=nightmare* && node index.js`

**Comment by FrostTheFox** [comment]
and paste me back the logs when it messes up

**Comment by FrostTheFox** [comment]
Gonna close this for now, report back on discord/here again if you experience it.
