### ISSUE TITLE
Country is not changing

### ISSUE THREAD

**Issue by impire123** [FrostTheFox/ptc-acc-gen#78]
I've change the default country to my country and after 1 try. I logged in and checked if the account got the right inputs and instead of having my country's input value it shows the default country which is US.

here's the config.js

var config = {
	// Starts gen from startNumber to endNumber, determining how many accounts are made
startNum:126,
endNum:150,
	
	// Creation Options
// Use nicknames file, or just append numbers to username?
nicknameFile:false,
 // If true generate a random password, If false set "password" field below
randomPassword:false,
// Saves a screenshot per account creation when set to true
screenshotResult:true,
// Saves a screenshot even if registration fails when set to true
screenshotOnFailure:true,
	
	// Creation Requirements
// Keep the '', User- & display name. Make sure any "(username + number)@domain.com" is 100% unique, and is 6 characters minimum, but under 14 characters after the numbers are applied.
username:"----",
// If you set randomPassword to 'false' above change this to your chosen password (so you have same password for all accounts)
password:"123456789",
// Enter your email address name. If your address is email@domain.com you'd enter 'email'
emailUser:"----",
// Domain of email address. If your address is email@domain.com  you'd enter 'domain.com'
emailDomain:"gmail.com",
// Location Latitude for initial login
latitude:"8.476916",
// Location Longitude for initial login
longitude:"124.631859",
// Country code (e.g. BE, FR, US, CA)
country:"PH",

// 2Captcha API key
useAutoCatcha: false,
captchaApiKey: "YOUR_2CAPTCHA_API_KEY_HERE"
};

module.exports = config;

**Comment by FrostTheFox** [comment]
Looking into it now.

**Comment by abcdandanda** [comment]
This line here : 
https://github.com/FrostTheFox/ptc-acc-gen/blob/master/index.js#L163

should be changed to 

`var els = document.getElementsByName("country");`

and it will work.

**Comment by FrostTheFox** [comment]
@abcdandanda seems correct, that change did change the country for me.

**Comment by FrostTheFox** [comment]
d0e0346

**Comment by impire123** [comment]
Thanks!
