### ISSUE TITLE
Servers are acting up

### ISSUE THREAD

**Issue by ic4roswings** [FrostTheFox/ptc-acc-gen#83]
I see the created account screen but the bat says 'Servers are acting up' and does not take the account as created why is that ?

**Comment by FrostTheFox** [comment]
Servers are acting up is on Nintendo's end, nothing we can do.

**Comment by Jonny-Johnson** [comment]
Are you sure there is no issue in the acc-gen? I have gotten this error for the last 10 tries and before it was every other time. Before, it showed a successful account registration but acc-gen said "acting up" and did it again. Then, the second or third try with the same account acc-gen would register it ok. Now, every time after I solve the Captcha, for a second the acc-gen Browser goes back to the top of the page and then starts a fresh try. 

When I try to access pokemon.com, it's all normal, albeit a bit slow maybe.
