### ISSUE TITLE
Hang on Fill Signup Page

### ISSUE THREAD

**Issue by coffman34** [FrostTheFox/ptc-acc-gen#9]
Sometimes there is a hang on Fill Signup Page.

The account is created, but the script won't budge past this point.

Restarting from the left off location continues to work until it hangs again.

Windows 10

**Comment by FrostTheFox** [comment]
We're aware of this issue. Not quite sure on the cause, but it is likely due to weirdness on PTC's end.

**Comment by razorasadsid** [comment]
Is this the same issue? For me it hands on this page after 1-2 accounts generated. http://image.prntscr.com/image/bbe97eba3dec49d89d80f1810eb22a02.png

**Comment by razorasadsid** [comment]
okay so it just seems to hang anywhere between 1-5 accounts on pretty much any page =/

**Comment by coffman34** [comment]
I think this is due to the page not loading properly, or the script not giving the page enough time to load. After activating window, you can see that the top logos do not load everytime that the script hangs. If you refresh the page in the window, then the script continues.

Where/how would we put a delay in on page load so that it gives the page a little extra time to load all of the page?

**Comment by tokyotapes** [comment]
Same issue here.  I can make about 5 or 6 accounts before it hangs and I have to restart it.

**Comment by FrostTheFox** [comment]
Support's been dropped for this tool. Please use https://github.com/skvvv/pikapy.
